---
title: "Chapter 1: *Introduction to Biostatistics*"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{chp01}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(knitr)
opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

```{r setup}
library(DanielBiostatistics10th)
```


# Example 1.4.1; Page 8 (10th ed), Page 7 (11th ed)
```{r}
class(EXA_C01_S04_01) # `EXA_C01_S04_01` is a 'data.frame' (a specific class defined in R)
dim(EXA_C01_S04_01) # dimension, number-row and number-column
head(EXA_C01_S04_01, n = 8L) # first `n` rows of a 'data.frame'
names(EXA_C01_S04_01) # column names of a 'data.frame'
EXA_C01_S04_01$AGE # use `$` to obtain one column from a 'data.frame' 
sampleRow(EXA_C01_S04_01, size = 10L, replace = FALSE) # to answer Example 1.4.1
```

# Example 1.4.2; Page 11 (10th ed), Page 10 (11th ed)
```{r}
EXA_C01_S04_01[seq.int(from = 4L, to = 166L, by = 18L), ]
```