---
title: "Chapter 5, *Some Important Sampling Distributions*"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{chp05}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(knitr)
opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

```{r setup}
library(DanielBiostatistics10th)
library(scales)
```



# Example 5.3.2
Page 142 (10th ed)
```{r}
aggregated_z(xbar = 190, sd = 12.7, n = 10L, null.value = 185.6, alternative = 'greater')
```

# Example 5.3.3
Page 143 (10th ed)
```{r}
(pnorm(125, mean = 120, sd = 15/sqrt(50)) - pnorm(115, mean = 120, sd = 15/sqrt(50))) |> 
  label_percent(accuracy = .1)() |>
  noquote()
(aggregated_z(125, sd = 15, n = 50L, null.value = 120, alternative = 'less')$p.value - 
  aggregated_z(115, sd = 15, n = 50L, null.value = 120, alternative = 'less')$p.value) |> 
  label_percent(accuracy = .1)() |>
  noquote()
```
Page 127 (11th ed)
```{r}
(aggregated_z(110, sd = 20, n = 50L, null.value = 100, alternative = 'less')$p.value - 
  aggregated_z(95, sd = 20, n = 50L, null.value = 100, alternative = 'less')$p.value) |> 
  label_percent(accuracy = .1)() |>
  noquote()
```

# Example 5.4.1
Page 145 (10th ed), Page 129 (11th ed) 
```{r}
aggregated_z(xbar = c(92, 105), sd = 20, n = 15L, null.value = 0, alternative = 'less') 
```

# Example 5.4.2
Page 148 (10th ed), 
```{r}
aggregated_z(xbar = 20, sd = c(15, 20), n = c(35L, 40L), null.value = c(45, 30), 
  alternative = 'greater')
```

# Example 5.5.1
Page 150 (10th ed), 
```{r}
prop_CLT(xbar = .4, n = 150L, null.value = .357, alternative = 'greater')
```
# Example 5.5.2
Page 152 (10th ed), 
```{r}
prop_CLT(xbar = .45, n = 200L, null.value = .51, alternative = 'less')
```

# Example 5.6.1
Page 155 (10th ed), 
```{r}
prop_CLT(xbar = .1, null.value = c(.28, .21), n = c(100L, 100L), alternative = 'greater')
```

# Example 5.6.2
Page 155 (10th ed), 
```{r}
prop_CLT(xbar = .05, null.value = c(.34, .26), n = c(250L, 200L), alternative = 'less')
```
